### ISSUE TITLE
CSS rules are not scoped to components

### ISSUE THREAD

**Issue by pinglu85** [pinglu85/robot-kinematics-visualization#25]
Example:

```svelte
<style>
 p {
   color: purple;
 }
</style>

<p>This is a paragraph.</p>
```

Expected CSS output: 

```css
p.svelte-ujowuv{
  color:purple
};
```

Actual CSS output: 

```CSS
p {
  color: purple;
}
```
The color of all `<p>` elements in the app is set to `purple`.
